version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
  backend:
    image: avb15214/backend
    # build:
    #   context: ../backend/foodgram
    #   dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/foodgram/static/
      - media_value:/app/foodgram/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: avb15214/frontend
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    volumes:
      - result_build:/app/result_build/build/
      - static_value:/app/result_build/build/static/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:      
      - backend
volumes:
  result_build:
  postgres_data:
  static_value:
  media_value:
