# Generated by Django 4.0.4 on 2022-05-19 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0005_recipe_recipeingredient_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-updated'], 'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='foods.RecipeIngredient', to='foods.ingredient', verbose_name='ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='recipe_shopping', to=settings.AUTH_USER_MODEL, verbose_name='в карте покупок у пользователей'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='foods.tag', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user_faworites',
            field=models.ManyToManyField(related_name='recipe_faworites', to=settings.AUTH_USER_MODEL, verbose_name='фаворит у пользователей'),
        ),
    ]
