# Generated by Django 4.0.4 on 2022-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_recipe_options_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='receipe_ingredient', through='foods.RecipeIngredient', to='foods.ingredient', verbose_name='ингредиенты'),
        ),
    ]
