# Generated by Django 4.0.4 on 2022-05-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredient', through='foods.RecipeIngredient', to='foods.ingredient', verbose_name='ингредиенты'),
        ),
    ]
