# Generated by Django 4.0.4 on 2022-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Картинка'),
        ),
    ]
