# Generated by Django 4.0.4 on 2022-05-28 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0013_alter_recipe_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user_faworites',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_favorites',
            field=models.ManyToManyField(blank=True, related_name='recipe_favorites', to=settings.AUTH_USER_MODEL, verbose_name='фаворит у пользователей'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
    ]
